name: Docker Build CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [test-ci, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ziknet-backend .

      - name: Docker Image Built Successfully
        run: echo "Docker image built and tested successfully 🎉"
